[package]
name = "fps-project"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "fps-core",
    "fps-cli",
    "fps-web",
]

[dependencies]

[dev-dependencies]
fps-core = { path = "fps-core" }
